floral/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views
app_name='myapp'

urlpatterns = [
	path('',views.index,name='index'),
	path('register/',views.register,name='register'),
	path('login/',views.login,name='login'),
	path('home/<int:id>',views.home,name='home'),
	path('logout/',views.logout,name='logout'),
	path('passwordchange/<int:id>',views.passwordchange,name='passwordchange'),
	path('viewprofile/<int:id>',views.viewprofile,name='viewprofile'),
	path('gallery/',views.gallery,name='gallery'),
	path('viewgallery/',views.viewgallery,name='viewgallery')
]

myapp/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
	Name=models.CharField(max_length=20)
	Email=models.EmailField()
	Place=models.CharField(max_length=20)
	Photo=models.ImageField(upload_to='media/')
	Password=models.CharField(max_length=20)

class Gallery(models.Model):
	Photo1=models.ImageField(upload_to='media2/',default='SOME STRING')
	Name=models.CharField(max_length=20)
	Price=models.IntegerField()
	

myapp/forms.py
from django import forms
from .models import Register,Gallery

class RegisterForm(forms.ModelForm):
	Password=forms.CharField(widget=forms.PasswordInput)
	CPassword=forms.CharField(widget=forms.PasswordInput)
	class Meta():
		model=Register
		fields='__all__'

class LoginForm(forms.ModelForm):
	Password=forms.CharField(widget=forms.PasswordInput)
	class Meta():
		model=Register
		fields=('Email','Password',)

class UpdatePassword(forms.Form):
	CurrentPassword=forms.CharField(widget=forms.PasswordInput)
	NewPassword=forms.CharField(widget=forms.PasswordInput)
	CPassword=forms.CharField(widget=forms.PasswordInput)

class UpdateGallery(forms.ModelForm):
	class Meta():
		model=Gallery
		fields='__all__'

myapp/views.py
from django.shortcuts import render,redirect
from .models import Register,Gallery
from .forms import RegisterForm,LoginForm,UpdatePassword,UpdateGallery
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
	return render(request,'index.html')
def register(request):
	if request.method=='POST':
		form=RegisterForm(request.POST or None,request.FILES)
		if form.is_valid():
			name=form.cleaned_data['Name']
			email=form.cleaned_data['Email']
			place=form.cleaned_data['Place']
			photo=form.cleaned_data['Photo']
			password=form.cleaned_data['Password']
			cpassword=form.cleaned_data['CPassword']

			ur=Register.objects.filter(Email=email).exists()
			if ur:
				msg='Email already exist'
				return render(request,'register.html',{'error':msg})
			elif password!=cpassword:
				msg='Password does not match'
				return render(request,'register.html',{'error':msg})
			else:
				reg=Register(Name=name,Email=email,Place=place,Photo=photo,Password=password)
				reg.save()
				return redirect('/')
	else:
		form=RegisterForm()
	return render(request,'register.html',{'form':form})

def login(request):
	if request.method=='POST':
		form=LoginForm(request.POST or None)
		if form.is_valid():
			email=form.cleaned_data['Email']
			password=form.cleaned_data['Password']

			ur=Register.objects.get(Email=email)
			if not ur:
				msg='Email does not exist'
				return render(request,'login.html',{'error':msg})
			elif ur.Password!=password:
				msg='Incorrect password'
				return render(request,'login.html',{'error':msg})
			else:
				request.session['sid']=ur.id
				return redirect('/home/%s' % ur.id)
	else:
		form=LoginForm()
	return render(request,'login.html',{'form':form})

def home(request,id):
	uid=request.session['sid']
	user=Register.objects.get(id=id)
	return render(request,'home.html',{'user':user})

def logout(request):
	try:
		del request.session['sid']
		return redirect('/')
	except:
		pass

def passwordchange(request,id):
	uid=request.session['sid']
	user=Register.objects.get(id=id)
	if request.method=='POST':
		form=UpdatePassword(request.POST)
		if form.is_valid():
			password=form.cleaned_data['CurrentPassword']
			newpass=form.cleaned_data['NewPassword']
			cpass=form.cleaned_data['CPassword']

			if user.Password!=password:
				msg='Incorrect Password'
				return render(request,'passwordchange.html',{'error':msg})
			elif newpass!=cpass:
				msg='Password Mismatch'
				return render(request,'passwordchange.html',{'error':msg})
			else:
				user.Password=newpass
				user.save()
				return redirect('/home/%s' % user.id)

	else:
		form=UpdatePassword()
	return render(request,'passwordchange.html',{'form':form})

def viewprofile(request,id):
	uid=request.session['sid']
	user=Register.objects.get(id=id)
	return render(request,'viewprofile.html',{'user':user})

def gallery(request):
	if request.method=='POST':
		form=UpdateGallery(request.POST,request.FILES)
		if form.is_valid():
			form.save()
		return redirect('/')

	else:
		form=UpdateGallery()
	return render(request,'gallery.html',{'form':form})

def viewgallery(request):
	data=Gallery.objects.all()
	return render(request,'viewgallery.html',{'data':data})


	

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Garden Truck</title>
<meta charset="utf-8">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/sForm.js' %}"></script>
<script src="{% static 'js/jquery.equalheights.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/tms-0.4.1.js' %}"></script>
<script src="{% static 'js/jquery.carouFredSel-6.1.0-packed.js' %}"></script>
<script	src="{% static 'js/jquery.touchSwipe.min.js' %}"></script>
<script>
$(window).load(function () {
    $('.slider')._TMS({
        show: 0,
        pauseOnHover: false,
        prevBu: '.prev',
        nextBu: '.next',
        playBu: false,
        duration: 800,
        preset: 'fade',
        pagination: false, //'.pagination',true,'<ul></ul>'
        pagNums: false,
        slideshow: 8000,
        numStatus: false,
        banners: true,
        waitBannerAnimation: false,
        progressBar: false
    })
});
$(window).load(
    function () {
        $('.carousel1').carouFredSel({
            auto: false,
            prev: '.prev1',
            next: '.next1',
            width: 1030,
            items: {
                visible: {
                    min: 1,
                    max: 4
                },
                height: 'auto',
                width: 157,
            },
            responsive: true,
            scroll: 1,
            mousewheel: false,
            swipe: {
                onMouse: true,
                onTouch: true
            }
        });
    });
</script>
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<link rel="stylesheet" media="screen" href="css/ie.css">
<![endif]-->
</head>
<body class="page1">
<header>
  
  <div class="container_12">
    <div class="grid_12">
      <div class="h_phone">Need Help? Call Us +1 (800) 123 4567</div>
      <h1><a href="index.html"><img src="{% static 'images/logo.png' %}" alt=""></a></h1>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="menu_block">
    <div class="container_12">
      <div class="grid_12">
        <div class="socials"><a href="#"></a><a href="#"></a></div>
        <div class="autor"> <a href="#">User Login</a> Social </div>
        <nav class="">
          <ul class="sf-menu">
            <li class="current"><a href="{% url 'myapp:register' %}">Register</a></li>
            <li class="with_ul"><a href="{% url 'myapp:login' %}">Login</a></li>
            <li><a href="{% url 'myapp:gallery' %}">AddImage</a>
              
              <ul>
                <li><a href="#"> Services List</a>
                  <ul>
                    <li><a href="#">Seeds</a></li>
                    <li><a href="#">Traits</a></li>
                    <li><a href="#">Safety Control</a></li>
                  </ul>
                </li>
                <li><a href="#">Overview</a></li>
                <li><a href="#">FAQS</a></li>
              </ul>
            </li>
            <li><a href="products.html">Products</a></li>
            <li><a href="blog.html">Blog</a></li>
            <li><a href="contacts.html">Contacts</a></li>
          </ul>
          
        </nav>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>
{% block content %}



{% endblock %}
<footer>
  <div class="container_12">
    <div class="grid_2">
      <div class="copy"> <a href="index.html" class="footer_logo"><img src="{% static 'images/footer_logo.png' %}"	alt=""></a> &copy; 2045 <a href="#">Privacy Policy</a> </div>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Delivery</a></li>
        <li><a href="#">Legal Notice</a></li>
        <li><a href="#">Terms and Conditions</a></li>
        <li><a href="#">About Us</a></li>
      </ul>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">New Products</a></li>
        <li><a href="#">Top Sellers</a></li>
        <li><a href="#">Specials</a></li>
        <li><a href="#">Manufacturers</a></li>
        <li><a href="#">Suppliers</a></li>
      </ul>
    </div>
    <div class="grid_2">
      <ul>
        <li><a href="#">Science &amp; Safety</a></li>
        <li><a href="#">Product </a></li>
        <li><a href="#">Our Brands</a></li>
        <li><a href="#">Agricultural </a></li>
        <li><a href="#">Traits &amp; Technologies</a></li>
      </ul>
    </div>
    <div class="grid_3 prefix_1">
      <h4>Newsletter</h4>
      <form id="newsletter" action="#">
        <div class="success">Your subscribe request has been sent!</div>
        <label class="email"> <span>Enter e-mail address</span>
          <input type="email" value="" >
          <a href="#" class="btn" data-type="submit">Subscribe</a> <span class="error">*This is not a valid email address.</span> </label>
      </form>
    </div>
    <div class="clear"></div>
  </div>
  <div class="f_bot">
    <div class="container_12">
      <div class="grid_12">Design by: <a href="{% static 'http://www.templatemonster.com/' %}">TemplateMonster.com</a></div>
    </div>
  </div>
</footer>
</body>
</html>

myapp/templates/gallery.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>gallery</title>
	
</head>
<body>
	{% block content %}
	
	<form action="{% url 'myapp:gallery' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
	<table>
		<tr>
			<td>
				{{form.as_table}}
			</td>
		</tr>
		<tr>
			<td>
				<input type="submit" value="Update">
			</td>
		</tr>
	</table>
	{% endblock %}

</body>
</html>

myapp/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>userhome</title>
</head>
<body>
	<form action="{% url 'myapp:index' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% if user %}

		<h1>Applicant Details </h1>
		<p>{{user.Name}}</p>
		<p>{{user.Email}}</p>
		<p>{{user.Place}}</p>

		<ul>
		<li><a href="{% url 'myapp:viewprofile' user.id %}">View Profile</a></li>
		<li><a href="{% url 'myapp:passwordchange' user.id %}">ChangePassword</a></li>
		<li><a href="{% url 'myapp:viewgallery' %}">View Gallery</a></li><br>
		<input type="submit" value="logout">
		{% endif %}

		
	</form>

</body>
</html>

myapp/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="slider-relative">
  <div class="slider-block">
    <div class="slider"> <a href="#" class="prev"></a> <a href="#" class="next"></a>
      <ul class="items">
       
        <li> <img src="{% static 'images/slide1.jpg' %}" alt="">
          <div class="banner">A new generation <br>
            <br>
            of farming</div>
        </li>
        <li> <img src="{% static 'images/slide2.jpg' %}" alt="">
          <div class="banner">Best food is<br>
            <br>
            natural food</div>
        </li>
        <li> <img src="{% static 'images/slide3.jpg' %}" alt="">
          <div class="banner">New agricultural <br>
            <br>
            technologies only</div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="content">
  <div class="black">
    <div class="page1_block">
      <div class="container_12">
        <div class="grid_12">
          <h2>Natural and fresh goods only!<br>
            <br>
            <br>
            The best agricultural technologies</h2>
        }
        </div>
        <div class="clear"></div>
      </div>
    </div>
    <div class="container_12">
      <div class="grid_3">
        <h3>Harvest</h3>
        <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
        <a href="#" class="btn">More</a> </div>
      <div class="grid_3">
        <h3>Cultivation</h3>
        <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
        <a href="#" class="btn">More</a> </div>
      <div class="grid_3">
        <h3>Protection</h3>
        <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
        <a href="#" class="btn">More</a> </div>
      <div class="grid_3">
        <h3>Treatment</h3>
        <div class="col1">Qhasellus id adipiscing nunc. Tonec velko augue et nula ehicula pretium. Yonecjol po consequat achoumsan erat ac vulputatwyt. Ut consectetur commodo mollis. Ut necrcilo fg tells interdum aliquete. Phasellus juihers daiprtyiscing nunc. Conec vel augue etjotr lnulla hylo vehicula pretium. Nonec consde equat gtmk accumsan erat ac vulptase.</div>
        <a href="#" class="btn">More</a> </div>
      <div class="clear"></div>
    </div>
  </div>
  <div class="white">
    <div class="container_12">
      <div class="grid_7">
        <h3>Company Products</h3>
        <img src="{% static 'images/page1_img1.jpg' %}" alt="" class="img_inner fleft">
        <div class="extra_wrapper">
          <div class="text1"> Aliquam placerat ligula eu sem facilj is semper porta sem pellentesque. </div>
          <p class="col1"><a class="col2" href="#">Click here</a> for more info about this free website template created by TemplateMonster.com </p>
          Lkhasellus id adipiscing nunc. Donecvelqq wr augue et nulla vehicula pretium. Donew ctryi weconsequat accumsan erat ac vu jo lputate. Kt consectetur commodo mollis. Ut necrci we tellus interdum aliquet. Johaseko kolo  lus id adipiscing nunc. Donec veldsak augue et nulr jver ehicula pretium. <br>
          <a href="#" class="btn">More</a> </div>
      </div>
      <div class="grid_4 prefix_1">
        <h3>Technologies</h3>
        <img src="{% static 'images/page1_img2.jpg' %}" alt="" class="img_inner fleft i1">
        <div class="extra_wrapper">
          <div class="col1"> <a href="#">Mklhasellus aed hadipiscin nury.</a> </div>
          Konecvel whjugute etew nulla vehiculuote. pretium. Donew ctryi weconsequat accure msan erat ac vu jo lputatesectetur. </div>
        <div class="clear cl1"></div>
        <img src="{% static 'images/page1_img3.jpg' %}" alt="" class="img_inner fleft i1">
        <div class="extra_wrapper">
          <div class="col1"> <a href="#">Uokhasellus id adipiscing nu.</a> </div>
          Honecvelqq whjugue et nulla vehiculuowe. Kjonecvelqq jugue et nulla vehiculoretium. Donew ctryi weconsequat accumsan. </div>
        <div class="clear cl2"></div>
        <img src="{% static 'images/page1_img4.jpg' %}" alt="" class="img_inner fleft i1">
        <div class="extra_wrapper">
          <div class="col1 "> <a href="#">Lkokhasellusuop adipiscing nuretilo kolitri.</a> </div>
          Kjonecvelqq jugue et nulla vehiculoretium. Donew ctryi weconsequat accumsan erat ac vu jo lputateconsectetur commodo. </div>
        <div class="clear"></div>
        <a href="#" class="btn">More</a> </div>
      <div class="clear"></div>
    </div>
  </div>
  <div class="gray">
    <div class="container_12">
      <div class="grid_12">
        <div class="car"> <a href="#" class="prev1"></a> <a href="#" class="next1"></a>
          <div class="car_div">
            <ul class="carousel1">
              <li><a href="#"><img src="{% static 'images/logo1.png' %}" alt=""></a></li>
              <li><a href="#"><img src="{% static 'images/logo2.png' %}" alt=""></a></li>
              <li><a href="#"><img src="{% static 'images/logo3.png' %}" alt=""></a></li>
              <li><a href="#"><img src="{% static 'images/logo4.png' %}" alt=""></a></li>
              <li><a href="#"><img src="{% static 'images/logo2.png' %}" alt=""></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</div>

{% endblock %}
<!-- <!DOCTYPE html>
<html>
<head>
  <title>index</title>
</head>
<body>
  <h1 align="center">WELCOME HOME</h1>
  <a href="{% url 'myapp:register' %}">Register</a><br>
  <a href="{% url 'myapp:login' %}">Login</a><br>
  <a href="{% url 'myapp:gallery' %}">AddImage</a>

</body>
</html> -->

myapp/templates/login.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>login</title>
</head>
<body>
	{% block content %}
	<div>
	<form action="{% url 'myapp:login' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{form.as_table}}
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" name="login">
				</td>
			</tr>
		</table>
		
	</form>
	</div>
	<dir style="height: 200px;">
		
	</dir>
	

	{% endblock %}

</body>
</html>

myapp/templates/passwordchange.html
<!DOCTYPE html>
<html>
<head>
	<title>ChangePassword</title>
</head>
<body>
	<form action="{% url 'myapp:passwordchange' user.id %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{form.as_table}}
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" value="change">
				</td>
			</tr>
		</table>
	</form>

</body>
</html>

myapp/templates/register.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
</head>
<body>
	{% block content %}
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tr>
				<td>
					{{form.as_table}}
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" value="Register">
				</td>
			</tr>
		</table>
	</form>
	<dir style="height: 100px;">
		
	</dir>
	{% endblock %}


</body>
</html>

myapp/templates/viewgallery.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>flowers</title>
</head>
<body>

	{% for x in data %}
		<img src="{{x.Photo1.url}}" height="100px" width="100px">
		<h3> Name:{{x.Name}}</h3>
		<h3> Price:{{x.Price}}</h3>
		<hr>
	{% endfor %}

</body>
</html>

myapp/templates/viewprofile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>profile</title>
</head>
<body>
	<h1>{{user.Name}}</h1>
	<img src="{{user.Photo.url}}" height="200px" width="200px" alt="photo">


</body>
</html>